# Generated by Django 5.1.1 on 2024-11-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_poll_made_by_option_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
