# Generated by Django 5.1.1 on 2024-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_style_poll_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='tailwind_classes',
            field=models.TextField(null=True),
        ),
    ]
